name: SGSI_Build


on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.rom_url }}" "ROM_URL config"
          required "${{ steps.config.outputs.build_type }}" "BUILD_TYPE config"
          required "${{ steps.config.outputs.os_type }}" "OS_TYPE config"
          required "${{ steps.config.outputs.zip_name }}" "ZIP_NAME config"
          required "${{ steps.config.outputs.version }}" "VERSION config"
          required "${{ steps.config.outputs.repack_name }}" "REPACK_NAME config"


      - name: Initializing Environment
        run: |
          sudo apt-get install -y git wget git zip unzip curl axel

      - name: Cloning SGSI source code
        run: |
          git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool

      - name: Setup sGSI tools requirements
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
          sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
        # sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
        # java -version

      - name: Build SGSI
        run: |
          cd  $GITHUB_WORKSPACE/SGSI-build-tool
          sudo bash ./url2SGSI.sh "${{ steps.config.outputs.rom_url }}" "${{ steps.config.outputs.os_type }}" "${{ steps.config.outputs.build_type }}"

      - name: Repack Output File
        run: |
          cd $GITHUB_WORKSPACE/SGSI-build-tool
          mv SGSI ${{ steps.config.outputs.repack_name }}
          ls
          
      - name: Upload FTP
        uses: dennisameling/ftp-upload-action@v1
        with:
          server: 3.16.255.161
          username: 114514
          password: Li123456
          secure: false
          local_dir: /home/runner/work/SGSI-build-action/SGSI-build-action/SGSI-build-tool/${{ steps.config.outputs.repack_name }}
          server_dir: ./
